package com.example.entity;

import javax.persistence.*;

/**
 * This is a class that models a PokemonMember.
 *
 * You should NOT make any modifications to this class.
 */
@Entity
@Table(name = "pokemon_members") // Specifies the table name
public class PokemonMember {
    /**
     * An id for this PokemonMember. You should use this as the Entity's ID.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    /**
     * Names of the Pokémon members (all are text)
     */
    @Column(name = "pokemon_1", nullable = false)
    private String pokemon1;

    @Column(name = "pokemon_2", nullable = false)
    private String pokemon2;

    @Column(name = "pokemon_3", nullable = false)
    private String pokemon3;

    @Column(name = "pokemon_4", nullable = false)
    private String pokemon4;

    @Column(name = "pokemon_5", nullable = false)
    private String pokemon5;

    @Column(name = "pokemon_6", nullable = false)
    private String pokemon6;

    /**
     * A default, no-args constructor, as well as correctly formatted getters and setters, are needed for
     * Jackson Objectmapper to work.
     */
    public PokemonMember() {
    }

    /**
     * When posting a new PokemonMember, the id can be generated by the database. In that case, a constructor without
     * id is needed.
     *
     * @param pokemon1
     * @param pokemon2
     * @param pokemon3
     * @param pokemon4
     * @param pokemon5
     * @param pokemon6
     */
    public PokemonMember(String pokemon1, String pokemon2, String pokemon3, String pokemon4, String pokemon5, String pokemon6) {
        this.pokemon1 = pokemon1;
        this.pokemon2 = pokemon2;
        this.pokemon3 = pokemon3;
        this.pokemon4 = pokemon4;
        this.pokemon5 = pokemon5;
        this.pokemon6 = pokemon6;
    }

    /**
     * When retrieving a PokemonMember from the database, all fields will be needed. In that case, a constructor with all
     * fields is needed.
     *
     * @param id
     * @param pokemon1
     * @param pokemon2
     * @param pokemon3
     * @param pokemon4
     * @param pokemon5
     * @param pokemon6
     */
    public PokemonMember(Integer id, String pokemon1, String pokemon2, String pokemon3, String pokemon4, String pokemon5, String pokemon6) {
        this.id = id;
        this.pokemon1 = pokemon1;
        this.pokemon2 = pokemon2;
        this.pokemon3 = pokemon3;
        this.pokemon4 = pokemon4;
        this.pokemon5 = pokemon5;
        this.pokemon6 = pokemon6;
    }

    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     *
     * @return id
     */
    public Integer getId() {
        return id;
    }

    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     *
     * @return pokemon1
     */
    public String getPokemon1() {
        return pokemon1;
    }

    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     *
     * @param pokemon1
     */
    public void setPokemon1(String pokemon1) {
        this.pokemon1 = pokemon1;
    }

    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     *
     * @return pokemon2
     */
    public String getPokemon2() {
        return pokemon2;
    }

    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     *
     * @param pokemon2
     */
    public void setPokemon2(String pokemon2) {
        this.pokemon2 = pokemon2;
    }

    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     *
     * @return pokemon3
     */
    public String getPokemon3() {
        return pokemon3;
    }

    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     *
     * @param pokemon3
     */
    public void setPokemon3(String pokemon3) {
        this.pokemon3 = pokemon3;
    }

    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     *
     * @return pokemon4
     */
    public String getPokemon4() {
        return pokemon4;
    }

    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     *
     * @param pokemon4
     */
    public void setPokemon4(String pokemon4) {
        this.pokemon4 = pokemon4;
    }

    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     *
     * @return pokemon5
     */
    public String getPokemon5() {
        return pokemon5;
    }

    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     *
     * @param pokemon5
     */
    public void setPokemon5(String pokemon5) {
        this.pokemon5 = pokemon5;
    }

    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     *
     * @return pokemon6
     */
    public String getPokemon6() {
        return pokemon6;
    }

    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     *
     * @param pokemon6
     */
    public void setPokemon6(String pokemon6) {
        this.pokemon6 = pokemon6;
    }

    /**
     * Overriding the default equals() method adds functionality to tell when two objects are identical, allowing
     * Assert.assertEquals and List.contains to function.
     *
     * @param obj the other object.
     * @return true if obj is equal to this object.
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PokemonMember other = (PokemonMember) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (pokemon1 == null) {
            if (other.pokemon1 != null)
                return false;
        } else if (!pokemon1.equals(other.pokemon1))
            return false;
        if (pokemon2 == null) {
            if (other.pokemon2 != null)
                return false;
        } else if (!pokemon2.equals(other.pokemon2))
            return false;
        if (pokemon3 == null) {
            if (other.pokemon3 != null)
                return false;
        } else if (!pokemon3.equals(other.pokemon3))
            return false;
        if (pokemon4 == null) {
            if (other.pokemon4 != null)
                return false;
        } else if (!pokemon4.equals(other.pokemon4))
            return false;
        if (pokemon5 == null) {
            if (other.pokemon5 != null)
                return false;
        } else if (!pokemon5.equals(other.pokemon5))
            return false;
        if (pokemon6 == null) {
            if (other.pokemon6 != null)
                return false;
        } else if (!pokemon6.equals(other.pokemon6))
            return false;
        return true;
    }

    /**
     * Overriding the default toString() method allows for easy debugging.
     *
     * @return a String representation of this class.
     */
    @Override
    public String toString() {
        return "PokemonMember{" +
                "id=" + id +
                ", pokemon1='" + pokemon1 + '\'' +
                ", pokemon2='" + pokemon2 + '\'' +
                ", pokemon3='" + pokemon3 + '\'' +
                ", pokemon4='" + pokemon4 + '\'' +
                ", pokemon5='" + pokemon5 + '\'' +
                ", pokemon6='" + pokemon6 + '\'' +
                '}';
    }
}
